### ISSUE TITLE
Create a similar datasets that is used in FB research

### ISSUE THREAD

**Issue by jackalhan** [CrowMind/code-retrieval#6]
In a worst case scenario (FB did not respond you), how can we create a similar datasets, what would be the sources and the steps we need to do that?

**Comment by Josephkready** [comment]
Link to datasets

https://drive.google.com/drive/folders/11TDRwtgbSx4VxIH3UMYUF-Uhi-LFUvLw?usp=sharing

**Comment by jackalhan** [comment]
Thank you Joseph,

**Comment by jackalhan** [comment]
I am now closing this ticket since we have another ticket related to this.
